{{/*
Miroir CDC Buffer PVC
Only rendered when cdc.buffer.primary=="pvc" or cdc.buffer.overflow=="pvc"
*/}}
{{- if eq (include "miroir.cdcPvcEnabled" .) "true" }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "miroir.fullname" . }}-cdc-pvc
  labels:
    {{- include "miroir.labels" . | nindent 4 }}
    app.kubernetes.io/component: miroir
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.miroir.cdc.buffer.pvc_size | default "10Gi" }}
  {{- if .Values.miroir.cdc.buffer.pvc_storage_class }}
  storageClassName: {{ .Values.miroir.cdc.buffer.pvc_storage_class }}
  {{- end }}
{{- end }}
