{{/*
Miroir Secret
*/}}
{{- if and .Values.miroir.replicas (not .Values.miroir.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miroir.fullname" . }}-secret
  labels:
    {{- include "miroir.labels" . | nindent 4 }}
    app.kubernetes.io/component: miroir
type: Opaque
stringData:
  masterKey: {{ .Values.miroir.masterKey | default (randAlphaNum 32) | quote }}
  nodeMasterKey: {{ .Values.meilisearch.masterKey | default (randAlphaNum 32) | quote }}
  adminApiKey: {{ .Values.miroir.adminApiKey | default (randAlphaNum 32) | quote }}
{{- end }}
