//! Schema migration system for TaskStore backends.
//!
//! Migrations are numbered SQL files embedded in the binary at compile time.
//! Each migration is applied exactly once, in order, and tracked in the
//! schema_versions table (SQLite) or schema_version key (Redis).
//!
//! ## Version checking
//!
//! - Binary version = max migration number compiled into the binary
//! - Store version = max migration applied to the store
//! - On startup: if store version > binary version, refuse to start with
//!   MiroirError::SchemaVersionAhead — operator must restore from backup or
//!   upgrade the binary.
//! - If binary version > store version, apply pending migrations.

use crate::Result;
use std::collections::BTreeMap;

/// A single migration with its version number and SQL content.
#[derive(Debug, Clone)]
pub struct Migration {
    /// Monotonic version number (e.g., 1 for 001_initial.sql)
    pub version: i64,
    /// Raw SQL to execute for this migration
    pub sql: &'static str,
}

/// Registry of all available migrations compiled into the binary.
#[derive(Debug, Clone)]
pub struct MigrationRegistry {
    /// Ordered map of version -> migration
    migrations: BTreeMap<i64, Migration>,
}

impl MigrationRegistry {
    /// Create a new registry from a list of migrations.
    ///
    /// Panics if migration versions are not unique.
    pub fn new(migrations: &[Migration]) -> Self {
        let mut map = BTreeMap::new();
        for m in migrations {
            if map.insert(m.version, m.clone()).is_some() {
                panic!("duplicate migration version: {}", m.version);
            }
        }
        Self { migrations: map }
    }

    /// Get the maximum migration version (the binary's schema version).
    pub fn max_version(&self) -> i64 {
        self.migrations.keys().last().copied().unwrap_or(0)
    }

    /// Get all migrations that need to be applied to reach the target version.
    ///
    /// Returns migrations with version > `current_version` in ascending order.
    pub fn pending_migrations(&self, current_version: i64) -> Vec<&Migration> {
        self.migrations
            .values()
            .filter(|m| m.version > current_version)
            .collect()
    }

    /// Validate that the store version is not ahead of the binary version.
    ///
    /// Returns an error if store_version > binary_version.
    pub fn validate_version(&self, store_version: i64) -> Result<()> {
        let binary_version = self.max_version();
        if store_version > binary_version {
            return Err(crate::MiroirError::SchemaVersionAhead {
                store_version,
                binary_version,
            });
        }
        Ok(())
    }
}

/// Build the migration registry from embedded migration files.
///
/// This function is generated by the macro that embeds migration files.
/// For now, we manually construct the registry with the available migrations.
pub fn build_registry() -> MigrationRegistry {
    MigrationRegistry::new(&[
        Migration {
            version: 1,
            sql: include_str!("../migrations/001_initial.sql"),
        },
        Migration {
            version: 2,
            sql: include_str!("../migrations/002_feature_tables.sql"),
        },
        Migration {
            version: 3,
            sql: include_str!("../migrations/003_task_registry_fields.sql"),
        },
    ])
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_registry_max_version() {
        let registry = MigrationRegistry::new(&[
            Migration {
                version: 1,
                sql: "CREATE TABLE foo (id INT);",
            },
            Migration {
                version: 2,
                sql: "ALTER TABLE foo ADD COLUMN name TEXT;",
            },
        ]);

        assert_eq!(registry.max_version(), 2);
    }

    #[test]
    fn test_pending_migrations() {
        let registry = MigrationRegistry::new(&[
            Migration {
                version: 1,
                sql: "CREATE TABLE foo (id INT);",
            },
            Migration {
                version: 2,
                sql: "ALTER TABLE foo ADD COLUMN name TEXT;",
            },
            Migration {
                version: 3,
                sql: "CREATE INDEX idx_foo_name ON foo(name);",
            },
        ]);

        // No pending migrations when at max version
        assert!(registry.pending_migrations(3).is_empty());

        // All migrations pending when at version 0
        let pending = registry.pending_migrations(0);
        assert_eq!(pending.len(), 3);
        assert_eq!(pending[0].version, 1);
        assert_eq!(pending[1].version, 2);
        assert_eq!(pending[2].version, 3);

        // Only migrations 2 and 3 pending when at version 1
        let pending = registry.pending_migrations(1);
        assert_eq!(pending.len(), 2);
        assert_eq!(pending[0].version, 2);
        assert_eq!(pending[1].version, 3);
    }

    #[test]
    fn test_validate_version_success() {
        let registry = MigrationRegistry::new(&[Migration {
            version: 5,
            sql: "CREATE TABLE foo (id INT);",
        }]);

        // Store at same version is OK
        registry.validate_version(5).unwrap();

        // Store behind binary is OK (will apply migrations)
        registry.validate_version(3).unwrap();

        // Fresh store (version 0) is OK
        registry.validate_version(0).unwrap();
    }

    #[test]
    fn test_validate_version_store_ahead() {
        let registry = MigrationRegistry::new(&[Migration {
            version: 3,
            sql: "CREATE TABLE foo (id INT);",
        }]);

        // Store ahead of binary should fail
        let result = registry.validate_version(5);
        assert!(result.is_err());
        match result.unwrap_err() {
            crate::MiroirError::SchemaVersionAhead {
                store_version,
                binary_version,
            } => {
                assert_eq!(store_version, 5);
                assert_eq!(binary_version, 3);
            }
            _ => panic!("expected SchemaVersionAhead error"),
        }
    }

    #[test]
    #[should_panic(expected = "duplicate migration version")]
    fn test_duplicate_version_panics() {
        MigrationRegistry::new(&[
            Migration {
                version: 1,
                sql: "CREATE TABLE foo (id INT);",
            },
            Migration {
                version: 1,
                sql: "CREATE TABLE bar (id INT);",
            },
        ]);
    }
}
